name: Docker
on:
  push:
    branches:
      - master
  create:
    tags:
      - '*'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Log into the Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: "Build and push images (latest)"
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker build -t ntrrg/hugo .
          docker build -t ntrrg/hugo -f extended.Dockerfile .
          docker push ntrrg/hugo
          docker push ntrrg/hugo:extended

      - name: "Build and push images (versions)"
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          docker build -t ntrrg/hugo:"${GITHUB_REF:11}" .
          docker build -t ntrrg/hugo:"${GITHUB_REF:11}-extended" -f extended.Dockerfile .
          docker push ntrrg/hugo:"${GITHUB_REF:11}"
          docker push ntrrg/hugo:"${GITHUB_REF:11}-extended"

